version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: zabbix-postgres
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal
    restart: unless-stopped

  zabbix-server:
    build:
      context: ./zabbix-server
      dockerfile: Dockerfile
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    depends_on:
      - postgres
    ports:
      - "10051:10051"
    networks:
      - internal
    restart: unless-stopped

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/Amsterdam
    expose:
      - "8080"
    networks:
      - internal
      - proxy
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    expose:
      - "3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - internal
      - proxy
    restart: unless-stopped

volumes:
  pgdata:
  grafana-storage:

networks:
  internal:
  proxy:
    external: true
